"""
Regression tests for StreamRingPipeline Tier 3 refactor.
These tests verify that the SubGNN path is unchanged after the refactor.
"""
import pathlib
import time
import pytest
import torch
import numpy as np
from src.gnn_models.subgnn_encoder import FraudRingClassifier
from src.gnn_models.lstm_classifier import LSTMFraudClassifier
from src.subgraph_matching.ifasi_index import IFASIIndex
from src.fraud_detection.streamring import StreamRingPipeline

# Golden fixture generated by running FraudRingClassifier (hidden_dim=32, embedding_dim=64,
# num_layers=2) on a deterministic 8-edge graph (torch.manual_seed(42), node features seeded
# per node). Regenerate if the SubGNN model architecture changes.
FIXTURE_DIR = pathlib.Path(__file__).parent / "fixtures"

FEAT_DIM = 32


class DummyTier1Model:
    def predict_proba(self, features):
        return np.column_stack([0.5 * np.ones(len(features)), 0.5 * np.ones(len(features))])


# Paper comparison configuration — used for parity test.
# The regression fixture uses smaller dims (hidden_dim=32) for test speed.
SUBGNN_PAPER_CONFIG = dict(hidden_dim=128, embedding_dim=64, num_layers=3)


@pytest.fixture
def subgnn_pipeline():
    """Pipeline with SubGNN Tier 3, deterministic weights."""
    torch.manual_seed(42)

    tier1 = DummyTier1Model()

    tier3 = FraudRingClassifier(node_feat_dim=FEAT_DIM, hidden_dim=32,
                                 embedding_dim=64, num_layers=2)
    tier3.eval()

    pipe = StreamRingPipeline(
        tier1_model=tier1,
        tier2_model=None,
        tier3_model=tier3,
        ifasi_index=IFASIIndex(),
        tier1_threshold=0.0,
        tier2_threshold=0.0,
        tier3_threshold=0.5,
        tier3_variant="subgnn",
        device="cpu",
    )

    for nid in range(20):
        pipe._node_features[nid] = torch.randn(
            FEAT_DIM, generator=torch.Generator().manual_seed(nid)).numpy()

    edges = [(0,1),(1,2),(2,3),(3,0),(4,5),(5,6),(6,4),(0,4)]
    for src, dst in edges:
        pipe._edge_index[0].append(src)
        pipe._edge_index[1].append(dst)
    pipe._num_nodes = 10

    return pipe


def test_subgnn_regression(subgnn_pipeline):
    """SubGNN Tier 3 output must match the golden fixture bit-for-bit."""
    golden = torch.load(FIXTURE_DIR / "tier3_golden.pt", weights_only=True)
    result = subgnn_pipeline._run_tier3(src=0, dst=1, timestamp=1000.0)
    assert result["is_fraud"] == golden["is_fraud"]
    assert abs(result["confidence"] - golden["confidence"]) < 1e-6, (
        f"Confidence drift: {result['confidence']} vs {golden['confidence']}"
    )


def test_node_timestamps_populated(subgnn_pipeline):
    """
    _update_graph_state must populate _node_timestamps after process_transaction.
    Catches the silent call-site bug: if call site is not updated, node_features
    gets passed as timestamp and _node_timestamps stays empty.
    """
    assert len(subgnn_pipeline._node_timestamps) == 0, "should start empty"
    subgnn_pipeline.process_transaction(
        src=0, dst=1, timestamp=999.0, value=1.0,
        node_features={0: np.zeros(FEAT_DIM), 1: np.zeros(FEAT_DIM)},
    )
    assert 0 in subgnn_pipeline._node_timestamps, "src node must be in _node_timestamps"
    assert 1 in subgnn_pipeline._node_timestamps, "dst node must be in _node_timestamps"
    assert isinstance(subgnn_pipeline._node_timestamps[0], float), (
        "_node_timestamps values must be floats, not dicts/None"
    )
    assert subgnn_pipeline._node_timestamps[0] == 999.0


def test_lstm_tier3_runs(subgnn_pipeline):
    """LSTM Tier 3 dispatch returns a valid result dict without crashing."""
    # Swap the model out for an LSTM and change the variant
    lstm_model = LSTMFraudClassifier(node_feat_dim=FEAT_DIM, hidden_dim=32,
                                      num_layers=1, output_dim=16, dropout=0.0)
    lstm_model.eval()
    subgnn_pipeline.tier3_model = lstm_model
    subgnn_pipeline.tier3_variant = "lstm"

    result = subgnn_pipeline._run_tier3(src=0, dst=1, timestamp=1000.0)
    assert "is_fraud" in result
    assert "confidence" in result
    assert isinstance(result["confidence"], float)
    assert 0.0 <= result["confidence"] <= 1.0


def test_invalid_tier3_variant_raises(subgnn_pipeline):
    """Invalid tier3_variant must raise ValueError at construction time."""
    tier1 = DummyTier1Model()
    tier3 = FraudRingClassifier(node_feat_dim=FEAT_DIM, hidden_dim=32,
                                 embedding_dim=64, num_layers=2)
    with pytest.raises(ValueError, match="tier3_variant"):
        StreamRingPipeline(
            tier1_model=tier1,
            tier2_model=None,
            tier3_model=tier3,
            ifasi_index=IFASIIndex(),
            tier3_variant="bad_value",
        )


# ---------------------------------------------------------------------------
# Task 5: Parameter parity
# ---------------------------------------------------------------------------

def test_parameter_count_parity():
    """
    LSTM and SubGNN Tier 3 models must have parameter counts within 10%.
    Tune LSTMFraudClassifier's hidden_dim default until this passes.
    """
    subgnn = FraudRingClassifier(node_feat_dim=FEAT_DIM, **SUBGNN_PAPER_CONFIG)
    lstm = LSTMFraudClassifier(node_feat_dim=FEAT_DIM)

    subgnn_params = sum(p.numel() for p in subgnn.parameters())
    lstm_params = sum(p.numel() for p in lstm.parameters())

    ratio = abs(subgnn_params - lstm_params) / subgnn_params
    assert ratio < 0.10, (
        f"Parameter count mismatch > 10%: SubGNN={subgnn_params}, "
        f"LSTM={lstm_params}, ratio={ratio:.2%}. "
        f"Adjust hidden_dim in LSTMFraudClassifier."
    )


# ---------------------------------------------------------------------------
# Task 6: End-to-end and latency tests
# ---------------------------------------------------------------------------


@pytest.fixture
def lstm_pipeline():
    """Pipeline with LSTM Tier 3."""
    torch.manual_seed(42)

    tier1 = DummyTier1Model()

    tier3 = LSTMFraudClassifier(node_feat_dim=FEAT_DIM)
    tier3.eval()

    pipe = StreamRingPipeline(
        tier1_model=tier1,
        tier2_model=None,
        tier3_model=tier3,
        ifasi_index=IFASIIndex(),
        tier1_threshold=0.0,
        tier2_threshold=0.0,
        tier3_threshold=0.5,
        tier3_variant="lstm",
        device="cpu",
    )
    return pipe


def _build_synthetic_stream(pipe, n=100, feat_dim=FEAT_DIM, seed=0):
    """Inject n synthetic transactions into a pipeline."""
    rng = np.random.RandomState(seed)
    for i in range(n):
        src = int(rng.randint(0, 20))
        dst = int(rng.randint(0, 20))
        ts = float(i * 10)
        feat = {src: rng.randn(feat_dim).astype("float32"),
                dst: rng.randn(feat_dim).astype("float32")}
        pipe.process_transaction(src, dst, timestamp=ts, value=1.0,
                                  node_features=feat)


def test_subgnn_end_to_end(subgnn_pipeline):
    """SubGNN pipeline runs 100 transactions without error."""
    _build_synthetic_stream(subgnn_pipeline)
    stats = subgnn_pipeline.get_statistics()
    assert stats["total_count"] == 100
    assert stats["tier3_count"] > 0, "Tier 3 should have been reached given threshold=0.0"


def test_lstm_end_to_end(lstm_pipeline):
    """LSTM pipeline runs 100 transactions without error."""
    _build_synthetic_stream(lstm_pipeline)
    stats = lstm_pipeline.get_statistics()
    assert stats["total_count"] == 100
    assert stats["tier3_count"] > 0, "Tier 3 should have been reached given threshold=0.0"


def test_tier3_latency_subgnn(subgnn_pipeline):
    """SubGNN _run_tier3 completes within 500ms on a 300-node subgraph (CPU)."""
    _build_synthetic_stream(subgnn_pipeline, n=300)
    # Warm up (first call may be slower due to PyTorch/C++ extension init)
    subgnn_pipeline._run_tier3(src=0, dst=1, timestamp=2999.0)
    start = time.perf_counter()
    subgnn_pipeline._run_tier3(src=0, dst=1, timestamp=3000.0)
    elapsed_ms = (time.perf_counter() - start) * 1000
    assert elapsed_ms < 500, f"SubGNN Tier 3 took {elapsed_ms:.1f}ms (>500ms budget)"


def test_tier3_latency_lstm(lstm_pipeline):
    """LSTM _run_tier3 completes within 500ms on a 300-node subgraph (CPU)."""
    _build_synthetic_stream(lstm_pipeline, n=300)
    # Warm up (first call may be slower due to PyTorch/C++ extension init)
    lstm_pipeline._run_tier3(src=0, dst=1, timestamp=2999.0)
    start = time.perf_counter()
    lstm_pipeline._run_tier3(src=0, dst=1, timestamp=3000.0)
    elapsed_ms = (time.perf_counter() - start) * 1000
    assert elapsed_ms < 500, f"LSTM Tier 3 took {elapsed_ms:.1f}ms (>500ms budget)"
